### ISSUE TITLE
[BUG]: Critical CSS extracted and not removed from styles.css

### ISSUE THREAD

**Issue by RodrigoTomeES** [PlayForm/Inline#82]
Hi,

I have this Astro config:

```ts
import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import sitemap from "@astrojs/sitemap";
import { loadEnv } from "vite";
import compress from "astro-compress";
import critters from "astro-critters";

const env = loadEnv(import.meta.env.MODE, process.cwd(), "");

// https://astro.build/config
export default defineConfig({
  site: env.SITE_URL,
  integrations: [tailwind(), sitemap(), critters(), compress()],
});
```

The result of this is that my critterial CSS was extracted to my index.html but that extracted CSS is not removed from my CSS file. However according to the crittiers library this CSS is removed from my CSS file.

![Captura de pantalla 2023-03-27 a las 16 52 30](https://user-images.githubusercontent.com/13077343/227977394-f2e52870-0a7f-492e-8b4f-026e1e5966ed.jpg)

![Captura de pantalla 2023-03-27 a las 16 53 43](https://user-images.githubusercontent.com/13077343/227977794-ce45b372-457c-4c4b-8fbc-dcf5198f0bc1.jpg)

Thanks for your awesome work!

**Comment by NikolaRHristov** [comment]
Hi, thank you for this issue. This is a known bug in [GoogleChromeLabs/critters](https://github.com/GoogleChromeLabs/critters). Future versions will have this fixed in [nikolaxhristov/critters](https://github.com/nikolaxhristov/critters)

**Comment by NikolaRHristov** [comment]
See https://github.com/astro-community/astro-critters/issues/67 https://github.com/astro-community/astro-critters/issues/1

**Comment by RodrigoTomeES** [comment]
@nikolaxhristov thanks for fix it! When will be available?

**Comment by NikolaRHristov** [comment]
It isn't fixed this is the issue to track it: https://github.com/nikolaxhristov/critters/issues/2

**Comment by RodrigoTomeES** [comment]
okay thanks, I thought that it was fixed because you close the issue 👍🏼

**Comment by RodrigoTomeES** [comment]
Hi, @NikolaRHristov where we can track this issue right now? because I saw that your critters repo was removed

**Comment by shishkin17** [comment]
@NikolaRHristov did you manage to fix this in your fork? Does it still exist?

**Comment by NikolaRHristov** [comment]
@RodrigoTomeES, @shishkin17 Sorry, I recently ran a script that closed all my issues. The repository is now moved at https://github.com/PlayForm/Critters. It's still not fixed.

**Comment by RodrigoTomeES** [comment]
@NikolaRHristov could you move the issue to that repo?

**Comment by NikolaRHristov** [comment]
Yup. https://github.com/PlayForm/Critters/issues/59
